# cargo-release configuration
# https://github.com/crate-ci/cargo-release

pre-release-hook = ["git", "cliff", "--tag", "v{{version}}", "-o", "CHANGELOG.md"]
pre-release-commit-message = "chore(release): {{version}}"
